### PR TITLE
locale.ja.properties (v5.5.3)

### PR DESCRIPTION
**Pull request by coolvitto**

### CODE REVIEW

**Comment by moltenform** [comment]
Thank you for providing this, I will merge it soon.

**Comment by moltenform** [comment]
Hi @coolvitto , thank you for adding the new translations for `Filter`, `Context`, and `Drop Selection`.

Were there problems with the existing locale.ja.properties? It looks like many translations were changed.

**Comment by coolvitto** [comment]
thank you very much.

**Comment by moltenform** [comment]
Can you describe the changes you made, the difference between `locale.ja.properties` and `locale.ja.properties (v5.5.3)`?

**Comment by coolvitto** [comment]
The Japanese version was created based on the English version of "locale.properties" from v5.5.3.

**Comment by moltenform** [comment]
Thanks, there was an existing version at https://github.com/moltenform/scite-files/blob/main/files/files/translations/locale.ja.properties but your new version does add about 5 new translations.

**Pull request merged**
